#ifndef INTER_PROCESS_MSG_CONFIG_H
#define INTER_PROCESS_MSG_CONFIG_H




#define MIN_PROSTHETIC_CTRL_2_NEURAL_NET_EVENT_SCHEDULING_DELAY SNN_SIM_PERIOD + 1000000 // 



#define MIN_NEURAL_NET_2_PROSTHETIC_CTRL_EVENT_SCHEDULING_DELAY PROSTHETIC_CONTROL_PERIOD + 1000000 // 





#endif
