#ifndef RT_TASKS_CONFIG_H
#define RT_TASKS_CONFIG_H

// System Time
#define SYSTIME_PERIODIC_PERIOD 							2000000		//2 ms
#define SYSTIME_PERIODIC_TASK_NAME						nam2num("SYSTIM")
#define SYSTIME_PERIODIC_TASK_PRIORITY 					1
#define SYSTIME_PERIODIC_STACK_SIZE 						10000
#define SYSTIME_PERIODIC_MSG_SIZE 							1000
#define SYSTIME_PERIODIC_CPU_ID 							0
#define SYSTIME_PERIODIC_CPU_TASK_ID						0	
#define SYSTIME_PERIODIC_SIGNAL 							0
#define SYSTIME_PERIODIC_POLICY 							SCHED_FIFO


// ExpControl
#define EXP_CONTROL_PERIOD 							SYSTIME_PERIODIC_PERIOD		//2 ms
#define EXP_CONTROL_TASK_NAME						nam2num("TRIALHND")
#define EXP_CONTROL_TASK_PRIORITY					300
#define EXP_CONTROL_STACK_SIZE 						10000
#define EXP_CONTROL_MSG_SIZE 						1000
#define EXP_CONTROL_POLICY 							SCHED_FIFO
#define EXP_CONTROL_CPU_ID							SYSTIME_PERIODIC_CPU_ID
#define EXP_CONTROL_CPU_TASK_ID			SYSTIME_PERIODIC_CPU_TASK_ID+1


// ExpDurationHandler
#define TRIAL_DURATION_HANDLER_PERIOD 						EXP_CONTROL_PERIOD		//1 ms
#define TRIAL_DURATION_HANDLER_TASK_NAME					nam2num("TRIALDUR")
#define TRIAL_DURATION_HANDLER_TASK_PRIORITY				301
#define TRIAL_DURATION_HANDLER_STACK_SIZE 					10000
#define TRIAL_DURATION_HANDLER_MSG_SIZE 						1000
#define TRIAL_DURATION_HANDLER_POLICY 						SCHED_FIFO
#define TRIAL_DURATION_HANDLER_CPU_ID						EXP_CONTROL_CPU_ID
#define TRIAL_DURATION_HANDLER_CPU_TASK_ID			EXP_CONTROL_CPU_TASK_ID + 1


// DioControl
#define DIO_CONTROL_PERIOD 						EXP_CONTROL_PERIOD		//1 ms
#define DIO_CONTROL_TASK_NAME					nam2num("ENVIHND")
#define DIO_CONTROL_TASK_PRIORITY				302
#define DIO_CONTROL_STACK_SIZE 					10000
#define DIO_CONTROL_MSG_SIZE 					1000
#define DIO_CONTROL_POLICY 						SCHED_FIFO
#define DIO_CONTROL_CPU_ID						EXP_CONTROL_CPU_ID
#define DIO_CONTROL_CPU_TASK_ID		TRIAL_DURATION_HANDLER_CPU_TASK_ID + 1


// DioCtrlDurationHandler
#define DIO_CTRL_DURATION_HANDLER_PERIOD 						EXP_CONTROL_PERIOD		//1 ms
#define DIO_CTRL_DURATION_HANDLER_TASK_NAME					nam2num("ENVIDHND")
#define DIO_CTRL_DURATION_HANDLER_TASK_PRIORITY				303
#define DIO_CTRL_DURATION_HANDLER_STACK_SIZE 					10000
#define DIO_CTRL_DURATION_HANDLER_MSG_SIZE 						1000
#define DIO_CTRL_DURATION_HANDLER_POLICY 						SCHED_FIFO
#define DIO_CTRL_DURATION_HANDLER_CPU_ID						EXP_CONTROL_CPU_ID
#define DIO_CTRL_DURATION_HANDLER_CPU_TASK_ID			DIO_CONTROL_CPU_TASK_ID + 1 


// ProstheticControl
#define PROSTHETIC_CONTROL_PERIOD 						EXP_CONTROL_PERIOD		//1 ms
#define PROSTHETIC_CONTROL_TASK_NAME					nam2num("MOBJHND")
#define PROSTHETIC_CONTROL_TASK_PRIORITY				304
#define PROSTHETIC_CONTROL_STACK_SIZE 					10000
#define PROSTHETIC_CONTROL_MSG_SIZE 					1000
#define PROSTHETIC_CONTROL_POLICY 						SCHED_FIFO
#define PROSTHETIC_CONTROL_CPU_ID						EXP_CONTROL_CPU_ID
#define PROSTHETIC_CONTROL_CPU_TASK_ID			DIO_CTRL_DURATION_HANDLER_CPU_TASK_ID + 1


// ProstheticCtrlDurationHandler
#define PROSTHETIC_CTRL_DURATION_HANDLER_PERIOD 						EXP_CONTROL_PERIOD		//1 ms
#define PROSTHETIC_CTRL_DURATION_HANDLER_TASK_NAME					nam2num("MOBDHND")
#define PROSTHETIC_CTRL_DURATION_HANDLER_TASK_PRIORITY					305
#define PROSTHETIC_CTRL_DURATION_HANDLER_STACK_SIZE 					10000
#define PROSTHETIC_CTRL_DURATION_HANDLER_MSG_SIZE 						1000
#define PROSTHETIC_CTRL_DURATION_HANDLER_POLICY 						SCHED_FIFO
#define PROSTHETIC_CTRL_DURATION_HANDLER_CPU_ID						EXP_CONTROL_CPU_ID
#define PROSTHETIC_CTRL_DURATION_HANDLER_CPU_TASK_ID			PROSTHETIC_CONTROL_CPU_TASK_ID + 1


// Exp Handler 2 Neural Network Messages Handler
#define EXP_CTRL_2_NEURAL_NET_MSGS_HANDLER_PERIOD 					EXP_CONTROL_PERIOD		//1 ms
#define EXP_CTRL_2_NEURAL_NET_MSGS_HANDLER_TASK_NAME				nam2num("TRTONN")
#define EXP_CTRL_2_NEURAL_NET_MSGS_HANDLER_TASK_PRIORITY			101
#define EXP_CTRL_2_NEURAL_NET_MSGS_HANDLER_STACK_SIZE 				10000
#define EXP_CTRL_2_NEURAL_NET_MSGS_HANDLER_MSG_SIZE		 		1000
#define EXP_CTRL_2_NEURAL_NET_MSGS_HANDLER_POLICY			 		SCHED_FIFO
#define EXP_CTRL_2_NEURAL_NET_MSGS_HANDLER_CPU_ID					EXP_CONTROL_CPU_ID
#define EXP_CTRL_2_NEURAL_NET_MSGS_HANDLER_CPU_TASK_ID	PROSTHETIC_CTRL_DURATION_HANDLER_CPU_TASK_ID + 1


// BlueSpike
#define BLUESPIKE_DAQ_PERIOD 							SAMPLING_INTERVAL*NUM_OF_SCAN		//1 ms
#define BLUESPIKE_DAQ_TASK_NAME						nam2num("BLUDAQ")
#define BLUESPIKE_DAQ_TASK_PRIORITY 					0	// highest priority
#define BLUESPIKE_DAQ_STACK_SIZE 						10000
#define BLUESPIKE_DAQ_MSG_SIZE 						1000
#define BLUESPIKE_DAQ_CPU_ID 							1
#define BLUESPIKE_DAQ_CPU_TASK_ID						0
#define BLUESPIKE_DAQ_SIGNAL 							0
#define BLUESPIKE_DAQ_POLICY 							SCHED_FIFO


// InSilicoSimulators
#define SNN_SIM_PERIOD						2000000		//1 ms
#define SNN_SIM_TASK_NAME					"SNN"
#define SNN_SIM_TASK_PRIORITY				202
#define SNN_SIM_STACK_SIZE 					10000
#define SNN_SIM_MSG_SIZE 					1000
#define SNN_SIM_POLICY 						SCHED_FIFO
#define SNN_SIM_CPU_ID						2


#define SNN_SIM_NUM_OF_DEDICATED_CPUS	2	// cpus startiing from SNN_SIM_CPU_ID are dedicated to SNN simulations


#define HYBRID_NETWORK_USER_SPACE_CPU_ID				0
#define HYBRID_NETWORK_USER_SPACE_CPU_THREAD_ID		0

#define SNN_SIM_USER_SPACE_CPU_ID			0
#define SNN_SIM_USER_SPACE_CPU_THREAD_ID	0

#define MAX_NUM_OF_RT_TASKS_PER_CPU	10









#endif
