#ifndef INTER_PROCESS_MSG_CONFIG_H
#define INTER_PROCESS_MSG_CONFIG_H




#define MIN_PROSTHETIC_CTRL_2_NEURAL_NET_EVENT_SCHEDULING_DELAY PROSTHETIC_CONTROL_PERIOD + SNN_SIM_PERIOD + 1000000 // 1 MS jitter buffer
//  MESSAGES FROM MOV OBJ HANDLER TO NEURAL NET


#define MIN_NEURAL_NET_2_PROSTHETIC_CTRL_EVENT_SCHEDULING_DELAY PROSTHETIC_CONTROL_PERIOD + SNN_SIM_PERIOD + 1000000 // 1 MS jitter buffer



#endif
